### PR TITLE
start testing node v12

### PR DESCRIPTION
**Pull request by adityapatadia**

### CODE REVIEW

**Comment by adityapatadia** [comment]
This PR is required for these tests to pass: https://github.com/lukechilds/cacheable-request/pull/81

**Comment by lukechilds** [comment]
Thanks, tests are failing.

**Comment by adityapatadia** [comment]
This needs to be merged. I will create new PR after that.

**Comment by lukechilds** [comment]
The point of the tests is to see whether a PR is ok to be merged.

Any PR needs to have all tests passing before it gets merged.

**Pull request closed without merging**
