### PR TITLE
Start testing node v12

### PR DESCRIPTION
**Pull request by adityapatadia**

### CODE REVIEW

**Comment by lukechilds** [comment]
Tests are failing.

**Comment by adityapatadia** [comment]
Okay. I will look into this.

**Comment by adityapatadia** [comment]
There is some issue with Keyv or keyv-test-suite. Can you take a look? https://travis-ci.org/lukechilds/keyv-sqlite/jobs/532699971

**Comment by adityapatadia** [comment]
Tests pass successfully in my local machine Node v12.

**Comment by lukechilds** [comment]
Have you tried `rm -rf node_modules && npm install` and checked the tests still pass?

**Comment by adityapatadia** [comment]
I installed node `12.1.0` using homebrew and it passes all tests. I tried your suggestion as well.

**Comment by adityapatadia** [comment]
The errors in Travis-CI are also weird with all tests throwing same error.

**Comment by jaredwray** [comment]
@adityapatadia - we are now moving to supporting node 12, 14, and 16. You can view this in the build status and on github actions: https://github.com/lukechilds/keyv-sqlite/actions/workflows/build.yaml

**Pull request closed without merging**
